# Yes, this file was generated by chatgipity.
# 
import pandas as pd
import matplotlib.pyplot as plt
from io import StringIO

rows = []
file_labels = []

with open("benchstat.csv") as f:
    lines = f.readlines()

# Step 1: Locate the sec/op section
for i, line in enumerate(lines):
    if "sec/op" in line and "CI" in line:
        # Extract file names from the line above
        file_line = lines[i - 1]
        file_parts = [p.strip() for p in file_line.split(",") if p.strip()]
        file_labels = [label.removesuffix(".txt") for label in file_parts]

        # Save data rows until next section
        j = i + 1
        while j < len(lines):
            if lines[j].strip() == "" or lines[j].startswith(",") or lines[j].lower().startswith("geomean"):
                break
            rows.append(lines[j])
            j += 1
        break

# Step 2: Read data rows into a DataFrame
csv_data = "".join(rows)
df_raw = pd.read_csv(StringIO(csv_data), header=None)

# Step 3: Extract benchmark size
df_raw["Label"] = df_raw[0].str.extract(r"size=(\d+)", expand=False).astype(int)

# Step 4: Identify sec/op columns (they repeat every 2 or 4 columns depending on how many files)
# We'll scan the sec/op header line to find column indices for 'sec/op'
secop_header = [h.strip() for h in lines[i].split(",")]
secop_indices = [idx for idx, val in enumerate(secop_header) if val == "sec/op"]

# Sanity check
if len(secop_indices) != len(file_labels):
    raise ValueError(f"Mismatch: Found {len(secop_indices)} 'sec/op' columns but {len(file_labels)} file labels")

# Step 5: Extract and convert sec/op to ns/op
df = df_raw[["Label"]].copy()

for col_idx, label in zip(secop_indices, file_labels):
    df[label] = df_raw[col_idx].astype(float) * 1e9  # sec -> ns

# Step 6: Plot
df = df.sort_values("Label")

plt.figure(figsize=(10, 6))
for label in file_labels:
    plt.plot(df["Label"], df[label], label=label, marker='o')

plt.xlabel("Input Size")
plt.ylabel("ns/op")
plt.legend()
plt.grid(True)
plt.xscale("log")
plt.yscale("log")
plt.tight_layout()
plt.savefig("plot.png")

